In [4]:
import pandas as pd

In [128]:
data = pd.read_csv('bloomberg.csv')

In [160]:
row_number = data.shape[0]
column_number = data.shape[1]

list_name =data.iloc[0][0]
#NEWS_HEAT_PUB_DNUMSTORIES=data.iloc[1]
#NEWS_HEAT_PUB_DMAX =data.iloc[2]
#NEWS_HEAT_READ_DAVG=data.iloc[3]
#NEWS_HEAT_READ_DMAX=data.iloc[4]
#NEWS_HEAT_PUB_DAVG =data.iloc[5]
#date =data.columns.tolist()[0:-1]

dataT=data.iloc[1:5].T
#data.iloc[1:5].T.iloc[0].tolist()

['\xef\xbb\xbfDate',
 '01/01/2003',
 '02/01/2003',
 '03/01/2003',
 '04/01/2003',
 '05/01/2003',
 '06/01/2003',
 '07/01/2003',
 '08/01/2003',
 '09/01/2003',
 '10/01/2003',
 '11/01/2003',
 '12/01/2003',
 '13/01/2003',
 '14/01/2003',
 '15/01/2003',
 '16/01/2003',
 '17/01/2003',
 '18/01/2003',
 '19/01/2003',
 '20/01/2003',
 '21/01/2003',
 '22/01/2003',
 '23/01/2003',
 '24/01/2003',
 '25/01/2003',
 '26/01/2003',
 '27/01/2003',
 '28/01/2003',
 '29/01/2003',
 '30/01/2003',
 '31/01/2003',
 '01/02/2003',
 '02/02/2003',
 '03/02/2003',
 '04/02/2003',
 '05/02/2003',
 '06/02/2003',
 '07/02/2003',
 '08/02/2003',
 '09/02/2003',
 '10/02/2003',
 '11/02/2003',
 '12/02/2003',
 '13/02/2003',
 '14/02/2003',
 '15/02/2003',
 '16/02/2003',
 '17/02/2003',
 '18/02/2003',
 '19/02/2003',
 '20/02/2003',
 '21/02/2003',
 '22/02/2003',
 '23/02/2003',
 '24/02/2003',
 '25/02/2003',
 '26/02/2003',
 '27/02/2003',
 '28/02/2003',
 '01/03/2003',
 '02/03/2003',
 '03/03/2003',
 '04/03/2003',
 '05/03/2003',
 '06/03/2003',
 '07/03/2003',
 '08/03/2003',
 '09/03/2003',
 '10/03/2003',
 '11/03/2003',
 '12/03/2003',
 '13/03/2003',
 '14/03/2003',
 '15/03/2003',
 '16/03/2003',
 '17/03/2003',
 '18/03/2003',
 '19/03/2003',
 '20/03/2003',
 '21/03/2003',
 '22/03/2003',
 '23/03/2003',
 '24/03/2003',
 '25/03/2003',
 '26/03/2003',
 '27/03/2003',
 '28/03/2003',
 '29/03/2003',
 '30/03/2003',
 '31/03/2003',
 '01/04/2003',
 '02/04/2003',
 '03/04/2003',
 '04/04/2003',
 '05/04/2003',
 '06/04/2003',
 '07/04/2003',
 '08/04/2003',
 '09/04/2003',
 '10/04/2003',
 '11/04/2003',
 '12/04/2003',
 '13/04/2003',
 '14/04/2003',
 '15/04/2003',
 '16/04/2003',
 '17/04/2003',
 '18/04/2003',
 '19/04/2003',
 '20/04/2003',
 '21/04/2003',
 '22/04/2003',
 '23/04/2003',
 '24/04/2003',
 '25/04/2003',
 '26/04/2003',
 '27/04/2003',
 '28/04/2003',
 '29/04/2003',
 '30/04/2003',
 '01/05/2003',
 '02/05/2003',
 '03/05/2003',
 '04/05/2003',
 '05/05/2003',
 '06/05/2003',
 '07/05/2003',
 '08/05/2003',
 '09/05/2003',
 '10/05/2003',
 '11/05/2003',
 '12/05/2003',
 '13/05/2003',
 '14/05/2003',
 '15/05/2003',
 '16/05/2003',
 '17/05/2003',
 '18/05/2003',
 '19/05/2003',
 '20/05/2003',
 '21/05/2003',
 '22/05/2003',
 '23/05/2003',
 '24/05/2003',
 '25/05/2003',
 '26/05/2003',
 '27/05/2003',
 '28/05/2003',
 '29/05/2003',
 '30/05/2003',
 '31/05/2003',
 '01/06/2003',
 '02/06/2003',
 '03/06/2003',
 '04/06/2003',
 '05/06/2003',
 '06/06/2003',
 '07/06/2003',
 '08/06/2003',
 '09/06/2003',
 '10/06/2003',
 '11/06/2003',
 '12/06/2003',
 '13/06/2003',
 '14/06/2003',
 '15/06/2003',
 '16/06/2003',
 '17/06/2003',
 '18/06/2003',
 '19/06/2003',
 '20/06/2003',
 '21/06/2003',
 '22/06/2003',
 '23/06/2003',
 '24/06/2003',
 '25/06/2003',
 '26/06/2003',
 '27/06/2003',
 '28/06/2003',
 '29/06/2003',
 '30/06/2003',
 '01/07/2003',
 '02/07/2003',
 '03/07/2003',
 '04/07/2003',
 '05/07/2003',
 '06/07/2003',
 '07/07/2003',
 '08/07/2003',
 '09/07/2003',
 '10/07/2003',
 '11/07/2003',
 '12/07/2003',
 '13/07/2003',
 '14/07/2003',
 '15/07/2003',
 '16/07/2003',
 '17/07/2003',
 '18/07/2003',
 '19/07/2003',
 '20/07/2003',
 '21/07/2003',
 '22/07/2003',
 '23/07/2003',
 '24/07/2003',
 '25/07/2003',
 '26/07/2003',
 '27/07/2003',
 '28/07/2003',
 '29/07/2003',
 '30/07/2003',
 '31/07/2003',
 '01/08/2003',
 '02/08/2003',
 '03/08/2003',
 '04/08/2003',
 '05/08/2003',
 '06/08/2003',
 '07/08/2003',
 '08/08/2003',
 '09/08/2003',
 '10/08/2003',
 '11/08/2003',
 '12/08/2003',
 '13/08/2003',
 '14/08/2003',
 '15/08/2003',
 '16/08/2003',
 '17/08/2003',
 '18/08/2003',
 '19/08/2003',
 '20/08/2003',
 '21/08/2003',
 '22/08/2003',
 '23/08/2003',
 '24/08/2003',
 '25/08/2003',
 '26/08/2003',
 '27/08/2003',
 '28/08/2003',
 '29/08/2003',
 '30/08/2003',
 '31/08/2003',
 '01/09/2003',
 '02/09/2003',
 '03/09/2003',
 '04/09/2003',
 '05/09/2003',
 '06/09/2003',
 '07/09/2003',
 '08/09/2003',
 '09/09/2003',
 '10/09/2003',
 '11/09/2003',
 '12/09/2003',
 '13/09/2003',
 '14/09/2003',
 '15/09/2003',
 '16/09/2003',
 '17/09/2003',
 '18/09/2003',
 '19/09/2003',
 '20/09/2003',
 '21/09/2003',
 '22/09/2003',
 '23/09/2003',
 '24/09/2003',
 '25/09/2003',
 '26/09/2003',
 '27/09/2003',
 '28/09/2003',
 '29/09/2003',
 '30/09/2003',
 '01/10/2003',
 '02/10/2003',
 '03/10/2003',
 '04/10/2003',
 '05/10/2003',
 '06/10/2003',
 '07/10/2003',
 '08/10/2003',
 '09/10/2003',
 '10/10/2003',
 '11/10/2003',
 '12/10/2003',
 '13/10/2003',
 '14/10/2003',
 '15/10/2003',
 '16/10/2003',
 '17/10/2003',
 '18/10/2003',
 '19/10/2003',
 '20/10/2003',
 '21/10/2003',
 '22/10/2003',
 '23/10/2003',
 '24/10/2003',
 '25/10/2003',
 '26/10/2003',
 '27/10/2003',
 '28/10/2003',
 '29/10/2003',
 '30/10/2003',
 '31/10/2003',
 '01/11/2003',
 '02/11/2003',
 '03/11/2003',
 '04/11/2003',
 '05/11/2003',
 '06/11/2003',
 '07/11/2003',
 '08/11/2003',
 '09/11/2003',
 '10/11/2003',
 '11/11/2003',
 '12/11/2003',
 '13/11/2003',
 '14/11/2003',
 '15/11/2003',
 '16/11/2003',
 '17/11/2003',
 '18/11/2003',
 '19/11/2003',
 '20/11/2003',
 '21/11/2003',
 '22/11/2003',
 '23/11/2003',
 '24/11/2003',
 '25/11/2003',
 '26/11/2003',
 '27/11/2003',
 '28/11/2003',
 '29/11/2003',
 '30/11/2003',
 '01/12/2003',
 '02/12/2003',
 '03/12/2003',
 '04/12/2003',
 '05/12/2003',
 '06/12/2003',
 '07/12/2003',
 '08/12/2003',
 '09/12/2003',
 '10/12/2003',
 '11/12/2003',
 '12/12/2003',
 '13/12/2003',
 '14/12/2003',
 '15/12/2003',
 '16/12/2003',
 '17/12/2003',
 '18/12/2003',
 '19/12/2003',
 '20/12/2003',
 '21/12/2003',
 '22/12/2003',
 '23/12/2003',
 '24/12/2003',
 '25/12/2003',
 '26/12/2003',
 '27/12/2003',
 '28/12/2003',
 '29/12/2003',
 '30/12/2003',
 '31/12/2003',
 '01/01/2004',
 '02/01/2004',
 '03/01/2004',
 '04/01/2004',
 '05/01/2004',
 '06/01/2004',
 '07/01/2004',
 '08/01/2004',
 '09/01/2004',
 '10/01/2004',
 '11/01/2004',
 '12/01/2004',
 '13/01/2004',
 '14/01/2004',
 '15/01/2004',
 '16/01/2004',
 '17/01/2004',
 '18/01/2004',
 '19/01/2004',
 '20/01/2004',
 '21/01/2004',
 '22/01/2004',
 '23/01/2004',
 '24/01/2004',
 '25/01/2004',
 '26/01/2004',
 '27/01/2004',
 '28/01/2004',
 '29/01/2004',
 '30/01/2004',
 '31/01/2004',
 '01/02/2004',
 '02/02/2004',
 '03/02/2004',
 '04/02/2004',
 '05/02/2004',
 '06/02/2004',
 '07/02/2004',
 '08/02/2004',
 '09/02/2004',
 '10/02/2004',
 '11/02/2004',
 '12/02/2004',
 '13/02/2004',
 '14/02/2004',
 '15/02/2004',
 '16/02/2004',
 '17/02/2004',
 '18/02/2004',
 '19/02/2004',
 '20/02/2004',
 '21/02/2004',
 '22/02/2004',
 '23/02/2004',
 '24/02/2004',
 '25/02/2004',
 '26/02/2004',
 '27/02/2004',
 '28/02/2004',
 '29/02/2004',
 '01/03/2004',
 '02/03/2004',
 '03/03/2004',
 '04/03/2004',
 '05/03/2004',
 '06/03/2004',
 '07/03/2004',
 '08/03/2004',
 '09/03/2004',
 '10/03/2004',
 '11/03/2004',
 '12/03/2004',
 '13/03/2004',
 '14/03/2004',
 '15/03/2004',
 '16/03/2004',
 '17/03/2004',
 '18/03/2004',
 '19/03/2004',
 '20/03/2004',
 '21/03/2004',
 '22/03/2004',
 '23/03/2004',
 '24/03/2004',
 '25/03/2004',
 '26/03/2004',
 '27/03/2004',
 '28/03/2004',
 '29/03/2004',
 '30/03/2004',
 '31/03/2004',
 '01/04/2004',
 '02/04/2004',
 '03/04/2004',
 '04/04/2004',
 '05/04/2004',
 '06/04/2004',
 '07/04/2004',
 '08/04/2004',
 '09/04/2004',
 '10/04/2004',
 '11/04/2004',
 '12/04/2004',
 '13/04/2004',
 '14/04/2004',
 '15/04/2004',
 '16/04/2004',
 '17/04/2004',
 '18/04/2004',
 '19/04/2004',
 '20/04/2004',
 '21/04/2004',
 '22/04/2004',
 '23/04/2004',
 '24/04/2004',
 '25/04/2004',
 '26/04/2004',
 '27/04/2004',
 '28/04/2004',
 '29/04/2004',
 '30/04/2004',
 '01/05/2004',
 '02/05/2004',
 '03/05/2004',
 '04/05/2004',
 '05/05/2004',
 '06/05/2004',
 '07/05/2004',
 '08/05/2004',
 '09/05/2004',
 '10/05/2004',
 '11/05/2004',
 '12/05/2004',
 '13/05/2004',
 '14/05/2004',
 '15/05/2004',
 '16/05/2004',
 '17/05/2004',
 '18/05/2004',
 '19/05/2004',
 '20/05/2004',
 '21/05/2004',
 '22/05/2004',
 '23/05/2004',
 '24/05/2004',
 '25/05/2004',
 '26/05/2004',
 '27/05/2004',
 '28/05/2004',
 '29/05/2004',
 '30/05/2004',
 '31/05/2004',
 '01/06/2004',
 '02/06/2004',
 '03/06/2004',
 '04/06/2004',
 '05/06/2004',
 '06/06/2004',
 '07/06/2004',
 '08/06/2004',
 '09/06/2004',
 '10/06/2004',
 '11/06/2004',
 '12/06/2004',
 '13/06/2004',
 '14/06/2004',
 '15/06/2004',
 '16/06/2004',
 '17/06/2004',
 '18/06/2004',
 '19/06/2004',
 '20/06/2004',
 '21/06/2004',
 '22/06/2004',
 '23/06/2004',
 '24/06/2004',
 '25/06/2004',
 '26/06/2004',
 '27/06/2004',
 '28/06/2004',
 '29/06/2004',
 '30/06/2004',
 '01/07/2004',
 '02/07/2004',
 '03/07/2004',
 '04/07/2004',
 '05/07/2004',
 '06/07/2004',
 '07/07/2004',
 '08/07/2004',
 '09/07/2004',
 '10/07/2004',
 '11/07/2004',
 '12/07/2004',
 '13/07/2004',
 '14/07/2004',
 '15/07/2004',
 '16/07/2004',
 '17/07/2004',
 '18/07/2004',
 '19/07/2004',
 '20/07/2004',
 '21/07/2004',
 '22/07/2004',
 '23/07/2004',
 '24/07/2004',
 '25/07/2004',
 '26/07/2004',
 '27/07/2004',
 '28/07/2004',
 '29/07/2004',
 '30/07/2004',
 '31/07/2004',
 '01/08/2004',
 '02/08/2004',
 '03/08/2004',
 '04/08/2004',
 '05/08/2004',
 '06/08/2004',
 '07/08/2004',
 '08/08/2004',
 '09/08/2004',
 '10/08/2004',
 '11/08/2004',
 '12/08/2004',
 '13/08/2004',
 '14/08/2004',
 '15/08/2004',
 '16/08/2004',
 '17/08/2004',
 '18/08/2004',
 '19/08/2004',
 '20/08/2004',
 '21/08/2004',
 '22/08/2004',
 '23/08/2004',
 '24/08/2004',
 '25/08/2004',
 '26/08/2004',
 '27/08/2004',
 '28/08/2004',
 '29/08/2004',
 '30/08/2004',
 '31/08/2004',
 '01/09/2004',
 '02/09/2004',
 '03/09/2004',
 '04/09/2004',
 '05/09/2004',
 '06/09/2004',
 '07/09/2004',
 '08/09/2004',
 '09/09/2004',
 '10/09/2004',
 '11/09/2004',
 '12/09/2004',
 '13/09/2004',
 '14/09/2004',
 '15/09/2004',
 '16/09/2004',
 '17/09/2004',
 '18/09/2004',
 '19/09/2004',
 '20/09/2004',
 '21/09/2004',
 '22/09/2004',
 '23/09/2004',
 '24/09/2004',
 '25/09/2004',
 '26/09/2004',
 '27/09/2004',
 '28/09/2004',
 '29/09/2004',
 '30/09/2004',
 '01/10/2004',
 '02/10/2004',
 '03/10/2004',
 '04/10/2004',
 '05/10/2004',
 '06/10/2004',
 '07/10/2004',
 '08/10/2004',
 '09/10/2004',
 '10/10/2004',
 '11/10/2004',
 '12/10/2004',
 '13/10/2004',
 '14/10/2004',
 '15/10/2004',
 '16/10/2004',
 '17/10/2004',
 '18/10/2004',
 '19/10/2004',
 '20/10/2004',
 '21/10/2004',
 '22/10/2004',
 '23/10/2004',
 '24/10/2004',
 '25/10/2004',
 '26/10/2004',
 '27/10/2004',
 '28/10/2004',
 '29/10/2004',
 '30/10/2004',
 '31/10/2004',
 '01/11/2004',
 '02/11/2004',
 '03/11/2004',
 '04/11/2004',
 '05/11/2004',
 '06/11/2004',
 '07/11/2004',
 '08/11/2004',
 '09/11/2004',
 '10/11/2004',
 '11/11/2004',
 '12/11/2004',
 '13/11/2004',
 '14/11/2004',
 '15/11/2004',
 '16/11/2004',
 '17/11/2004',
 '18/11/2004',
 '19/11/2004',
 '20/11/2004',
 '21/11/2004',
 '22/11/2004',
 '23/11/2004',
 '24/11/2004',
 '25/11/2004',
 '26/11/2004',
 '27/11/2004',
 '28/11/2004',
 '29/11/2004',
 '30/11/2004',
 '01/12/2004',
 '02/12/2004',
 '03/12/2004',
 '04/12/2004',
 '05/12/2004',
 '06/12/2004',
 '07/12/2004',
 '08/12/2004',
 '09/12/2004',
 '10/12/2004',
 '11/12/2004',
 '12/12/2004',
 '13/12/2004',
 '14/12/2004',
 '15/12/2004',
 '16/12/2004',
 '17/12/2004',
 '18/12/2004',
 '19/12/2004',
 '20/12/2004',
 '21/12/2004',
 '22/12/2004',
 '23/12/2004',
 '24/12/2004',
 '25/12/2004',
 '26/12/2004',
 '27/12/2004',
 '28/12/2004',
 '29/12/2004',
 '30/12/2004',
 '31/12/2004',
 '01/01/2005',
 '02/01/2005',
 '03/01/2005',
 '04/01/2005',
 '05/01/2005',
 '06/01/2005',
 '07/01/2005',
 '08/01/2005',
 '09/01/2005',
 '10/01/2005',
 '11/01/2005',
 '12/01/2005',
 '13/01/2005',
 '14/01/2005',
 '15/01/2005',
 '16/01/2005',
 '17/01/2005',
 '18/01/2005',
 '19/01/2005',
 '20/01/2005',
 '21/01/2005',
 '22/01/2005',
 '23/01/2005',
 '24/01/2005',
 '25/01/2005',
 '26/01/2005',
 '27/01/2005',
 '28/01/2005',
 '29/01/2005',
 '30/01/2005',
 '31/01/2005',
 '01/02/2005',
 '02/02/2005',
 '03/02/2005',
 '04/02/2005',
 '05/02/2005',
 '06/02/2005',
 '07/02/2005',
 '08/02/2005',
 '09/02/2005',
 '10/02/2005',
 '11/02/2005',
 '12/02/2005',
 '13/02/2005',
 '14/02/2005',
 '15/02/2005',
 '16/02/2005',
 '17/02/2005',
 '18/02/2005',
 '19/02/2005',
 '20/02/2005',
 '21/02/2005',
 '22/02/2005',
 '23/02/2005',
 '24/02/2005',
 '25/02/2005',
 '26/02/2005',
 '27/02/2005',
 '28/02/2005',
 '01/03/2005',
 '02/03/2005',
 '03/03/2005',
 '04/03/2005',
 '05/03/2005',
 '06/03/2005',
 '07/03/2005',
 '08/03/2005',
 '09/03/2005',
 '10/03/2005',
 '11/03/2005',
 '12/03/2005',
 '13/03/2005',
 '14/03/2005',
 '15/03/2005',
 '16/03/2005',
 '17/03/2005',
 '18/03/2005',
 '19/03/2005',
 '20/03/2005',
 '21/03/2005',
 '22/03/2005',
 '23/03/2005',
 '24/03/2005',
 '25/03/2005',
 '26/03/2005',
 '27/03/2005',
 '28/03/2005',
 '29/03/2005',
 '30/03/2005',
 '31/03/2005',
 '01/04/2005',
 '02/04/2005',
 '03/04/2005',
 '04/04/2005',
 '05/04/2005',
 '06/04/2005',
 '07/04/2005',
 '08/04/2005',
 '09/04/2005',
 '10/04/2005',
 '11/04/2005',
 '12/04/2005',
 '13/04/2005',
 '14/04/2005',
 '15/04/2005',
 '16/04/2005',
 '17/04/2005',
 '18/04/2005',
 '19/04/2005',
 '20/04/2005',
 '21/04/2005',
 '22/04/2005',
 '23/04/2005',
 '24/04/2005',
 '25/04/2005',
 '26/04/2005',
 '27/04/2005',
 '28/04/2005',
 '29/04/2005',
 '30/04/2005',
 '01/05/2005',
 '02/05/2005',
 '03/05/2005',
 '04/05/2005',
 '05/05/2005',
 '06/05/2005',
 '07/05/2005',
 '08/05/2005',
 '09/05/2005',
 '10/05/2005',
 '11/05/2005',
 '12/05/2005',
 '13/05/2005',
 '14/05/2005',
 '15/05/2005',
 '16/05/2005',
 '17/05/2005',
 '18/05/2005',
 '19/05/2005',
 '20/05/2005',
 '21/05/2005',
 '22/05/2005',
 '23/05/2005',
 '24/05/2005',
 '25/05/2005',
 '26/05/2005',
 '27/05/2005',
 '28/05/2005',
 '29/05/2005',
 '30/05/2005',
 '31/05/2005',
 '01/06/2005',
 '02/06/2005',
 '03/06/2005',
 '04/06/2005',
 '05/06/2005',
 '06/06/2005',
 '07/06/2005',
 '08/06/2005',
 '09/06/2005',
 '10/06/2005',
 '11/06/2005',
 '12/06/2005',
 '13/06/2005',
 '14/06/2005',
 '15/06/2005',
 '16/06/2005',
 '17/06/2005',
 '18/06/2005',
 '19/06/2005',
 '20/06/2005',
 '21/06/2005',
 '22/06/2005',
 '23/06/2005',
 '24/06/2005',
 '25/06/2005',
 '26/06/2005',
 '27/06/2005',
 '28/06/2005',
 '29/06/2005',
 '30/06/2005',
 '01/07/2005',
 '02/07/2005',
 '03/07/2005',
 '04/07/2005',
 '05/07/2005',
 '06/07/2005',
 '07/07/2005',
 '08/07/2005',
 '09/07/2005',
 '10/07/2005',
 '11/07/2005',
 '12/07/2005',
 '13/07/2005',
 '14/07/2005',
 '15/07/2005',
 '16/07/2005',
 '17/07/2005',
 '18/07/2005',
 '19/07/2005',
 '20/07/2005',
 '21/07/2005',
 '22/07/2005',
 '23/07/2005',
 '24/07/2005',
 '25/07/2005',
 '26/07/2005',
 '27/07/2005',
 '28/07/2005',
 '29/07/2005',
 '30/07/2005',
 '31/07/2005',
 '01/08/2005',
 '02/08/2005',
 '03/08/2005',
 '04/08/2005',
 '05/08/2005',
 '06/08/2005',
 '07/08/2005',
 '08/08/2005',
 '09/08/2005',
 '10/08/2005',
 '11/08/2005',
 '12/08/2005',
 '13/08/2005',
 '14/08/2005',
 '15/08/2005',
 '16/08/2005',
 '17/08/2005',
 '18/08/2005',
 '19/08/2005',
 '20/08/2005',
 '21/08/2005',
 '22/08/2005',
 '23/08/2005',
 '24/08/2005',
 '25/08/2005',
 '26/08/2005',
 '27/08/2005',
 '28/08/2005',
 '29/08/2005',
 '30/08/2005',
 '31/08/2005',
 '01/09/2005',
 '02/09/2005',
 '03/09/2005',
 '04/09/2005',
 '05/09/2005',
 '06/09/2005',
 '07/09/2005',
 '08/09/2005',
 '09/09/2005',
 '10/09/2005',
 '11/09/2005',
 '12/09/2005',
 '13/09/2005',
 '14/09/2005',
 '15/09/2005',
 '16/09/2005',
 '17/09/2005',
 '18/09/2005',
 '19/09/2005',
 '20/09/2005',
 '21/09/2005',
 '22/09/2005',
 '23/09/2005',
 '24/09/2005',
 '25/09/2005',
 ...]

In [157]:
dataT.columns=dataT.iloc[0].tolist()
df =dataT.drop(dataT.index[:1])
df.index.name='Date'
df =df.reset_index()
for datenumber in xrange(len(df['Date'])):
    temp =df['Date'][datenumber].split('/')
    date_replace = temp[2]+'-'+temp[1]+'-'+temp[0]
    df.set_value(datenumber,'Date',date_replace)

,Date,NEWS_HEAT_PUB_DNUMSTORIES,NEWS_HEAT_PUB_DMAX,NEWS_HEAT_READ_DAVG,NEWS_HEAT_READ_DMAX
0,2003-01-01,NaN,NaN,NaN,NaN
1,2003-01-02,NaN,NaN,NaN,NaN
2,2003-01-03,NaN,NaN,NaN,NaN
3,2003-01-04,NaN,NaN,NaN,NaN
4,2003-01-05,NaN,NaN,NaN,NaN
5,2003-01-06,NaN,NaN,NaN,NaN
6,2003-01-07,NaN,NaN,NaN,NaN
7,2003-01-08,NaN,NaN,NaN,NaN
8,2003-01-09,NaN,NaN,NaN,NaN
9,2003-01-10,NaN,NaN,NaN,NaN
10,2003-01-11,NaN,NaN,NaN,NaN
11,2003-01-12,NaN,NaN,NaN,NaN
12,2003-01-13,NaN,NaN,NaN,NaN
13,2003-01-14,NaN,NaN,NaN,NaN
14,2003-01-15,NaN,NaN,NaN,NaN
15,2003-01-16,NaN,NaN,NaN,NaN
16,2003-01-17,NaN,NaN,NaN,NaN
17,2003-01-18,NaN,NaN,NaN,NaN
18,2003-01-19,NaN,NaN,NaN,NaN
19,2003-01-20,NaN,NaN,NaN,NaN
20,2003-01-21,NaN,NaN,NaN,NaN
21,2003-01-22,NaN,NaN,NaN,NaN
22,2003-01-23,NaN,NaN,NaN,NaN
23,2003-01-24,NaN,NaN,NaN,NaN
24,2003-01-25,NaN,NaN,NaN,NaN
25,2003-01-26,NaN,NaN,NaN,NaN
26,2003-01-27,NaN,NaN,NaN,NaN
27,2003-01-28,NaN,NaN,NaN,NaN
28,2003-01-29,NaN,NaN,NaN,NaN
29,2003-01-30,NaN,NaN,NaN,NaN
...,...,...,...,...,...
5124,2017-01-11,23,2,1,4
5125,2017-01-12,10,1,0,0
5126,2017-01-13,9,1,0,0
5127,2017-01-14,NaN,NaN,NaN,NaN
5128,2017-01-15,NaN,NaN,NaN,NaN
5129,2017-01-16,5,1,0,0
5130,2017-01-17,29,2,0,0
5131,2017-01-18,44,3,0,0
5132,2017-01-19,11,1,0,0
5133,2017-01-20,11,2,0,0
5134,2017-01-21,NaN,NaN,NaN,NaN
5135,2017-01-22,NaN,NaN,NaN,NaN
5136,2017-01-23,17,1,0,0
5137,2017-01-24,7,1,0,2
5138,2017-01-25,10,1,0,1
5139,2017-01-26,25,3,0,0
5140,2017-01-27,15,2,0,0
5141,2017-01-28,NaN,NaN,NaN,NaN
5142,2017-01-29,NaN,NaN,NaN,NaN
5143,2017-01-30,6,1,0,0
5144,2017-01-31,28,4,0,3
5145,2017-02-01,12,1,0,0
5146,2017-02-02,21,3,0,0
5147,2017-02-03,4,0,0,0
5148,2017-02-04,NaN,NaN,NaN,NaN
5149,2017-02-05,NaN,NaN,NaN,NaN
5150,2017-02-06,13,2,0,0
5151,2017-02-07,7,1,0,0
5152,2017-02-08,6,1,0,0
5153,2017-02-09,NaN,NaN,NaN,NaN

In [159]:
import sqlite3
conn= sqlite3.connect("test.db")

df.to_sql(list_name, conn, if_exists='append', index=False)
data[[0,1]]
row_list = data[[0]].to_csv(None, header=False, index=False).split('\n')

In [120]:
df.shape[0]

5154